moveit_servo:
  # Incoming Command Topics
  command_in_type: "speed_units"
  cartesian_command_in_topic: ~/delta_twist_cmds
  joint_command_in_topic: ~/delta_joint_cmds
  pose_command_in_topic: ~/pose_target_cmds

  # Output
  command_out_type: trajectory_msgs/JointTrajectory
  command_out_topic: /scaled_joint_trajectory_controller/joint_trajectory

  # Robot Properties
  publish_period: 0.004
  low_latency_mode: false
  publish_joint_positions: true
  publish_joint_velocities: false
  publish_joint_accelerations: false

  move_group_name: ur_manipulator
  planning_frame: base_link
  ee_frame: tool0
  robot_link_command_frame: tool0

  # Topics to Listen To
  joint_topic: /joint_states
  status_topic: ~/status
  monitored_planning_scene_topic: /monitored_planning_scene

  # Safety & Collision
  check_collisions: true
  collision_check_rate: 10.0
  collision_check_type: threshold_distance
  self_collision_proximity_threshold: 0.01
  scene_collision_proximity_threshold: 0.02
  incoming_command_timeout: 0.1

  # Singularity Handling
  lower_singularity_threshold: 17.0
  hard_stop_singularity_threshold: 30.0
  
  # Joint Limit Margins (Added to prevent other errors)
  joint_limit_margins: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  leaving_singularity_threshold_multiplier: 2.0