/servo_node:
  ros__parameters:
    moveit_servo:
      command_in_type: "speed_units"

      publish_period: 0.004
      low_latency_mode: false

      command_out_type: trajectory_msgs/JointTrajectory
      command_out_topic: /scaled_joint_trajectory_controller/joint_trajectory

      publish_joint_positions: true
      publish_joint_velocities: false
      publish_joint_accelerations: false

      move_group_name: ur_manipulator
      planning_frame: base_link
      ee_frame: tool0
      robot_link_command_frame: tool0

      cartesian_command_in_topic: ~/delta_twist_cmds
      joint_command_in_topic: ~/delta_joint_cmds
      joint_topic: /joint_states
      status_topic: ~/status

      incoming_command_timeout: 0.1
      is_primary_planning_scene_monitor: false
      monitored_planning_scene_topic: /monitored_planning_scene

      check_collisions: true
      collision_check_rate: 5.0
      collision_check_type: threshold_distance
      self_collision_proximity_threshold: 0.01
      scene_collision_proximity_threshold: 0.02

      lower_singularity_threshold: 30.0
      hard_stop_singularity_threshold: 60.0
