/**:
  ros__parameters:
    ## Properties of incoming commands
    command_in_type: "speed_units"
    scale:
      linear: 0.6
      rotational: 0.8
      joint: 0.5

    ## Properties of outgoing commands
    publish_period: 0.01
    low_pass_filter_coeff: 2.0
    command_out_type: "trajectory_msgs/JointTrajectory"
    publish_joint_positions: true
    publish_joint_velocities: true
    publish_joint_accelerations: false

    ## MoveIt properties
    move_group_name: "ur_manipulator"
    planning_frame: "base_link"
    is_primary_planning_scene_monitor: true
    ee_frame_name: "tool0"
    robot_link_command_frame: "base_link"

    ## Stopping behaviour
    incoming_command_timeout: 0.1
    num_outgoing_halt_msgs_to_publish: 4

    ## Singularity thresholds
    lower_singularity_threshold: 15.0
    hard_stop_singularity_threshold: 30.0
    joint_limit_margins: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

    ## Topic names (ABSOLUTE PATHS)
    cartesian_command_in_topic: "/servo_server/delta_twist_cmds"
    joint_topic: "/joint_states_servo"
    status_topic: "/servo_server/status"
    command_out_topic: "/scaled_joint_trajectory_controller/joint_trajectory"

    ## Collision checking
    check_collisions: false
    collision_check_rate: 10.0
