use_gazebo: false

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  linear: 0.4
  rotational: 0.8
  joint: 0.5

## Properties of outgoing commands
publish_period: 0.01
low_pass_filter_coeff: 2.0

# What type of topic does your robot driver expect?
command_out_type: "trajectory_msgs/JointTrajectory"

# What to publish?
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

## MoveIt properties
move_group_name: "ur_manipulator"
planning_frame: "base_link"

## Other frames
ee_frame_name: "tool0"
robot_link_command_frame: "base_link"
camera_frame: "camera_link"

## Stopping behaviour
incoming_command_timeout: 0.1
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold: 17.0
hard_stop_singularity_threshold: 30.0
joint_limit_margin: 0.1
leaving_singularity_threshold_multiplier: 2.0

## Topic names
cartesian_command_in_topic: "/servo_server/delta_twist_cmds"
joint_command_in_topic: "/servo_server/delta_joint_cmds"
joint_topic: "/joint_states"
status_topic: "/servo_server/status"
command_out_topic: "/scaled_joint_trajectory_controller/joint_trajectory"

## Collision checking
check_collisions: true
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
